export const DEVICE_SCALE = 0.025

export const CAMERA_DEFAULT_POSITION = [15, 15, 30]
export const CAMERA_DEFAULT_TARGET = [0, 0, 0]
export const CAMERA_DEFAULT_ZOOM = 2

export const ENV_MAP_DEFAULT_INTENSITY = 0.6

export const AMBIENT_LIGHT_DEFAULT_INTENSITY = 0.4
export const AMBIENT_LIGHT_DEFAULT_COLOR = '#0000ff'
